### ISSUE TITLE
Run examples

### ISSUE THREAD

**Issue by LinHuican** [gaoxiang12/ORBSLAM2_with_pointcloud_map#1]
Hello!
May ask you a running examples? I have no idea about how to set the start_index and end_index?

**Comment by gaoxiang12** [comment]
@LinHuican 
For running examples just follow the Examples/ directory in the original ORB_SLAM2 because I don't change the system interface of ORB SLAM. It has both dataset and live examples. When you run RGBD examples you will find a point cloud map is updating.

**Comment by LinHuican** [comment]
OK!
Thank you!
