### ISSUE TITLE
The color of dense pointcloud map is black and white

### ISSUE THREAD

**Issue by melodybinbin** [gaoxiang12/ORBSLAM2_with_pointcloud_map#10]
Hello,Dr. Gao.My issue is as following.
After I build the ORB_SLAM2_modified,I execute the ./bin/rgbd_tum to run a dataset of TUM.However,the color of dense pointcloud map is black and white,without color information.
When I build the ORBSLAM2_with_pointcloud_map/ORB_SLAM2_modified/Examples/ROS/ORB_SLAM2,I execute the ORBSLAM2_with_pointcloud_map/ORB_SLAM2_modified/Examples/ROS/ORB_SLAM2/RGBD,
to run the device of kinect2 real time.
Similarly,there is no color of the dense pointcloud map.
I need some help,thanks.

**Comment by melodybinbin** [comment]
And,what's the differences between the ORB_SLAM2_modified  and the orbslam2_modified.zip?

**Comment by taochenshh** [comment]
@melodybinbin Have you figured it out? I also saw that the point cloud has no cloud rendering. I modified some code, but did not succeed.

@gaoxiang12 Could you please help us with this issue? Thanks.

**Comment by gaoxiang12** [comment]
Thank you, please use the code in "ORB_SLAM2_modified/" directory, not the zipped file. It is an earlier version and I don't have time to clear it now. 
About the problem that the viewer doesn't show point cloud's color, please check if ORB SLAM has converted the RGB images into grayscale ones. Check the reading parts in System.cc and Tracking.cc and if so, change those codes to make the point cloud can really read the color.

**Comment by taochenshh** [comment]
Thanks, that solved my problem.

**Comment by UThinkD** [comment]
@CTTC  I have met the same problem. The pointcloud has no color information. How you solve the problem? Can you give me a help?

**Comment by thornsu** [comment]
I have this problem too, I remember it's color in the past. But in that version, I must install g2o_with_orbslam2, it's in zipped file. I would not to install the past version because that g2o version is different with now.

**Comment by lizhihuit** [comment]
@CTTC I have met the same problem.The  color of dense pointcloud map is black and white,without color information.Can you give me a help? Thankyou

**Comment by melodybinbin** [comment]
As Dr. Gao said above, use the code in "ORB_SLAM2_modified/" directory, not the zipped file.
Firstly, declare mImRGB in Tracking.h as following:
    Frame mCurrentFrame;
    cv::Mat mImRGB;//declared
    cv::Mat mImGray;
Secondly, modify the Tracking.cc as following:
Modified place 1:
cv::Mat Tracking::GrabImageRGBD(const cv::Mat &imRGB,const cv::Mat &imD, const double &timestamp)
{
    mImRGB = imRGB;//Modified place 1
    mImGray = imRGB;
    ......

Modified place 2:
mpPointCloudMapping->insertKeyFrame( pKF, this->mImGray, this->mImDepth );//change the mImGray to mImRGB as next row 
mpPointCloudMapping->insertKeyFrame( pKF, this->mImRGB, this->mImDepth );//Modified place 2

Finally,execute build.sh and build_ros.sh to realize color dense pointcloud map with data sets and kinect v2 respectively.

**Comment by XZZZ9** [comment]
> 

按你改的不对啊报错

**Comment by NeXT1995** [comment]
您好，你的邮件，杨沂林已经收到，我会尽快查收的，谢谢！
