### ISSUE TITLE
编译成功后运行出现 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xielhjia** [gaoxiang12/ORBSLAM2_with_pointcloud_map#31]
编译成功后出现Segmentation fault (core dumped)

调试后发现是pointcloudmapping.cc里第122行至125行导致出错

 PointCloud::Ptr tmp(new PointCloud());
        voxel.setInputCloud( globalMap );
        voxel.filter( *tmp );
        globalMap->swap( *tmp );

把这几行注释掉之后程序可运行，但是效果不太好，想问下为什么这几行会出现段错误？

**Comment by xielhjia** [comment]
已经解决，换eigen版本为3.2之后就没问题了

**Comment by JinXiangLai** [comment]
感谢，确实是这个问题，请问这是什么原因呢？

**Comment by JinXiangLai** [comment]
> 已经解决，换eigen版本为3.2之后就没问题了

感谢，确实是这个问题，请问这是什么原因呢？

**Comment by JinXiangLai** [comment]
> > 已经解决，换eigen版本为3.2之后就没问题了
> 
> 感谢，确实是这个问题，请问这是什么原因呢？

查了一下，好像是PCL1.8没有使用C++11编译，所以出现段错误
