### ISSUE TITLE
size of the global map is 0

### ISSUE THREAD

**Issue by RahmanMifta** [gaoxiang12/ORBSLAM2_with_pointcloud_map#35]
When i run the ROS/RGBD, there is no output in the viewer and the size of global map is 0. But, when i run Examples/RGB-D, then i get point cloud in the viewer. Can anyone help me to solve the problem?

**Comment by gaoxiang12** [comment]
Please check if your config yaml if right or not. I remember there is a leaf size parameter added into the original ORB-SLAM's yaml file.
