### ISSUE TITLE
高博士，我编译您这个点云版的example下的ROS包时，出现@GLIBCXX_3.4.21’未定义的引用错误

### ISSUE THREAD

**Issue by w8128835** [gaoxiang12/ORBSLAM2_with_pointcloud_map#39]
报错具体如下：libboost_filesystem.so：对‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21’未定义的引用；
libboost_filesystem.so：对‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21’未定义的引用；
......
/libboost_filesystem.so：对‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21’未定义的引用;
我列出了其中几条，但是都是@GLIBCXX_3.4.21’未定义的引用这个错误，请问您能帮我解惑吗？提前谢谢您啦

**Comment by gaoxiang12** [comment]
编译环境是什么？看上去是环境问题。

**Comment by w8128835** [comment]
高博，我用Ubuntu14.04，系统版本如下：
Linux version 4.4.0-148-generic (buildd@lgw01-amd64-014) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) )
我用的opencv版本是2.4.8，pcl用的是1.7；

但是编译原版orbslam2可以通过，编译原版orbslam2时显示如下信息:
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4

**Comment by w8128835** [comment]
高博士，请问我能换ubuntu16.04，然后拿kinectv1 把ros下订阅的图像topic改了运行您这个包吗？

**Comment by gaoxiang12** [comment]
可以，随你想怎么做都行，图像从数据集读和从ROS读没区别。

**Comment by w8128835** [comment]
好的，我正在换系统尝试，谢谢您啦
