### ISSUE TITLE
What is the difference between your g2o and the original g2o?

### ISSUE THREAD

**Issue by zzzzzq** [gaoxiang12/ORBSLAM2_with_pointcloud_map#4]
Hello! I just downloaded your code and successfully make g2o bag and ORB_SLAM bag. But when I run the node, the program broke down. Then I made some attempts and found that when I use the original version of g2o the program won't break down, and when I use your g2o it will break down on my computer. After that when I use ORB_SLAM with the original g2o on a turtlebot in gazebo, everything goes well but there is no dense point cloud. I can see the "viewer" window and there is nothing in it nut a triangle claw. I upload the screenshot in this question. Can you please tell me any idea how can I fix this bug? Thank you very much!
![screenshot from 2016-11-21 21 38 26](https://cloud.githubusercontent.com/assets/17118335/20484789/d3628e38-b033-11e6-9f2c-3f13cdeae09b.png)

**Comment by gaoxiang12** [comment]
Hi, I have not tested it in ROS. How do you use the ORB-SLAM? Do you grab the RGBD data and feed it into ORB-SLAM? The original one or the changed one?

**Comment by zzzzzq** [comment]
I have solved this problem. I think it is because a wierd place in pointcloudmapping.cc. From line 119 to line 123, you create a new PointCloud::Ptr tmp and swap it with globalMap. I don't understand these lines. But in my case, after swaping pointer globalMap points to a null object, the following view.showCloud() just show this empty pointer. As the result there is no map in the viewer. I commented the swap line and deleted tmp and it works. 
Because I also made some change in ORB so I didn't use your version of g2o but the original, and the project works well.
By the way, I am from the next door of your university and have read many blogs you wrote on the Internet about SLAM. I'm very excited to talk to you about this project. I'd like to say thanks to you for your helping   newcomers like me to learn SLAM!

**Comment by gaoxiang12** [comment]
Sure, then I will close this issue. You can move my modification into yours and combine them. Generally speaking I build a point cloud in each keyframe and put it into a global map according to the pose given by ORB-SLAM. This is very easy to implement but some people need it so I put it here. 
Thank you for your support.

**Comment by qixuxiang** [comment]
hi@ziqi-zhang ，I meet same issue,too.I commented the swap line and finally I can also get a pcd file,but I cannot see the real-time reconstruction ,here is my code after line 123

```
        PointCloud::Ptr (new PointCloud());
        voxel.setInputCloud( globalMap );

        //globalMap->swap( *tmp );
        viewer.showCloud( globalMap );
        cout << "show global map, size=" << globalMap->points.size() << endl;
        lastKeyframeSize = N;
    }
    pcl::PCDWriter pcdwriter;
    pcdwriter.write<pcl::PointXYZRGBA>("global.pcd", *globalMap);//write global point cloud map and save to a pcd file 
```

would you please help me ?How can i change the code to see real-time point cloud reconstruction map in the viewer.THX a lot !
